// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by rive_telemetry_core.
// Source: c:\dev\rive_telemetry\demo\assets\demo_3.riv

import 'dart:ui' as ui;

import 'package:rive/rive.dart' as rive;

abstract final class RiveIntegrationMetadata {
  static const schemaVersion = 1;
  static const source = 'c:\\dev\\rive_telemetry\\demo\\assets\\demo_3.riv';
  static const status = 'partialUsable';
}

abstract final class RiveIntegrationArtboards {
  static const mainArtboard = 'MainArtboard';
  static const faceTransitions = 'Face-transitions';
  static const faceMood = 'Face-mood';
  static const faceReactns = 'Face-reactns';
}

abstract final class RiveIntegrationStateMachines {
  static const mainArtboardMainStateMachine = 'MainStateMachine';
  static const faceTransitionsFaceTransitionSm = 'Face transition SM';
  static const faceMoodFaceMoodSm = 'Face Mood SM';
  static const faceReactnsFaceReactionSm = 'Face Reaction SM';
}

abstract final class RiveIntegrationAnimations {
  static const mainArtboardConfetti = 'confetti';
  static const mainArtboardSpin = 'spin';
  static const mainArtboardPointAtUser = 'pointAtUser';
  static const mainArtboardPuffCheeks = 'puffCheeks';
  static const mainArtboardEyeRoll = 'eyeRoll';
  static const mainArtboardMock = 'mock';
  static const mainArtboardCelebrate = 'celebrate';
  static const mainArtboardHeadShake = 'headShake';
  static const mainArtboardNod = 'nod';
  static const mainArtboardNeutral = 'neutral';
  static const mainArtboardListening = 'listening';
  static const mainArtboardWaveHand = 'waveHand';
  static const mainArtboardThinking = 'thinking';
  static const mainArtboardDefaultPose = 'defaultPose';
  static const faceTransitionsFlicker = 'flicker';
  static const faceMoodEncouraging = 'encouraging';
  static const faceMoodPlayful = 'playful';
  static const faceMoodSurprise = 'surprise';
  static const faceMoodEyeRoll = 'eyeRoll';
  static const faceMoodThinking = 'thinking';
  static const faceMoodHappy = 'happy';
  static const faceMoodTalkLow = 'talkLow';
  static const faceMoodNeutral = 'neutral';
  static const faceMoodTalkActive = 'talkActive';
  static const faceMoodTalkNeutral = 'talkNeutral';
  static const faceReactnsThinking = 'thinking';
  static const faceReactnsPuffyCheeks = 'puffyCheeks';
  static const faceReactnsConfetti = 'confetti';
  static const faceReactnsEyeRoll = 'eyeRoll';
  static const faceReactnsListen = 'listen';
  static const faceReactnsTalkLow = 'talkLow';
  static const faceReactnsNeutral = 'neutral';
  static const faceReactnsTalkActive = 'talkActive';
  static const faceReactnsTalkNeutral = 'talkNeutral';
}

abstract final class RiveIntegrationViewModels {
  static const viewModel1 = 'ViewModel1';
}

final class RiveIntegrationViewModel1Binding {
  const RiveIntegrationViewModel1Binding(this.instance);

  final rive.ViewModelInstance instance;

  static const viewModelName = 'ViewModel1';
  static const instanceName = 'Instance';

  RiveNumberViewModelProperty get confettiCount => RiveNumberViewModelProperty(instance, 'confettiCount');
  RiveNumberViewModelProperty get confettiSize => RiveNumberViewModelProperty(instance, 'confettiSize');
  RiveColorViewModelProperty get confettiColor => RiveColorViewModelProperty(instance, 'confettiColor');
  RiveTriggerViewModelProperty get confetti => RiveTriggerViewModelProperty(instance, 'confetti');
  RiveTriggerViewModelProperty get spin => RiveTriggerViewModelProperty(instance, 'spin');
  RiveTriggerViewModelProperty get pointAtUser => RiveTriggerViewModelProperty(instance, 'pointAtUser');
  RiveTriggerViewModelProperty get puffCheeks => RiveTriggerViewModelProperty(instance, 'puffCheeks');
  RiveTriggerViewModelProperty get mock => RiveTriggerViewModelProperty(instance, 'mock');
  RiveNumberViewModelProperty get stance => RiveNumberViewModelProperty(instance, 'stance');
  RiveColorViewModelProperty get colorGradientDark => RiveColorViewModelProperty(instance, 'colorGradientDark');
  RiveColorViewModelProperty get colorPrimary => RiveColorViewModelProperty(instance, 'colorPrimary');
  RiveColorViewModelProperty get colorShadowDark => RiveColorViewModelProperty(instance, 'colorShadowDark');
  RiveColorViewModelProperty get colorShadowLight => RiveColorViewModelProperty(instance, 'colorShadowLight');
  RiveTriggerViewModelProperty get eyeRoll => RiveTriggerViewModelProperty(instance, 'eyeRoll');
  RiveTriggerViewModelProperty get nod => RiveTriggerViewModelProperty(instance, 'nod');
  RiveTriggerViewModelProperty get headShake => RiveTriggerViewModelProperty(instance, 'headShake');
  RiveTriggerViewModelProperty get waveHand => RiveTriggerViewModelProperty(instance, 'waveHand');
  RiveNumberViewModelProperty get talkLevel => RiveNumberViewModelProperty(instance, 'talkLevel');
  RiveNumberViewModelProperty get mood => RiveNumberViewModelProperty(instance, 'mood');
  RiveColorViewModelProperty get faceColor => RiveColorViewModelProperty(instance, 'faceColor');
}

final class RiveNumberViewModelProperty {
  const RiveNumberViewModelProperty(this.instance, this.name);
  final rive.ViewModelInstance instance;
  final String name;
  double? get value => instance.number(name)?.value;
  bool set(num value) {
    final property = instance.number(name);
    if (property == null) return false;
    property.value = value.toDouble();
    instance.requestAdvance();
    return true;
  }
}

final class RiveBooleanViewModelProperty {
  const RiveBooleanViewModelProperty(this.instance, this.name);
  final rive.ViewModelInstance instance;
  final String name;
  bool? get value => instance.boolean(name)?.value;
  bool set(bool value) {
    final property = instance.boolean(name);
    if (property == null) return false;
    property.value = value;
    instance.requestAdvance();
    return true;
  }
}

final class RiveStringViewModelProperty {
  const RiveStringViewModelProperty(this.instance, this.name);
  final rive.ViewModelInstance instance;
  final String name;
  String? get value => instance.string(name)?.value;
  bool set(String value) {
    final property = instance.string(name);
    if (property == null) return false;
    property.value = value;
    instance.requestAdvance();
    return true;
  }
}

final class RiveColorViewModelProperty {
  const RiveColorViewModelProperty(this.instance, this.name);
  final rive.ViewModelInstance instance;
  final String name;
  ui.Color? get value => instance.color(name)?.value;
  bool set(ui.Color value) {
    final property = instance.color(name);
    if (property == null) return false;
    property.value = value;
    instance.requestAdvance();
    return true;
  }
}

final class RiveEnumViewModelProperty {
  const RiveEnumViewModelProperty(this.instance, this.name);
  final rive.ViewModelInstance instance;
  final String name;
  String? get value => instance.enumerator(name)?.value;
  bool set(String value) {
    final property = instance.enumerator(name);
    if (property == null) return false;
    property.value = value;
    instance.requestAdvance();
    return true;
  }
}

final class RiveTriggerViewModelProperty {
  const RiveTriggerViewModelProperty(this.instance, this.name);
  final rive.ViewModelInstance instance;
  final String name;
  bool fire() {
    final property = instance.trigger(name);
    if (property == null) return false;
    property.trigger();
    instance.requestAdvance();
    return true;
  }
}

final class RiveUnsupportedViewModelProperty {
  const RiveUnsupportedViewModelProperty(this.instance, this.name);
  final rive.ViewModelInstance instance;
  final String name;
}
