import 'codegen.dart';
import 'metadata.dart';

class RiveFlutterGeneratorOptions {
  const RiveFlutterGeneratorOptions({
    this.classPrefix = 'RiveIntegration',
    this.includeHeader = true,
  });

  final String classPrefix;
  final bool includeHeader;
}

class RiveFlutterGeneratedFile {
  const RiveFlutterGeneratedFile({
    required this.source,
    required this.diagnostics,
  });

  final String source;
  final List<RiveCodegenDiagnostic> diagnostics;
}

class RiveFlutterIntegrationGenerator {
  const RiveFlutterIntegrationGenerator({
    this.planner = const RiveCodegenPlanner(),
  });

  final RiveCodegenPlanner planner;

  RiveFlutterGeneratedFile generate(
    RiveMetadata metadata, {
    RiveFlutterGeneratorOptions options = const RiveFlutterGeneratorOptions(),
  }) {
    final plan = planner.build(metadata);
    final diagnostics = [...plan.diagnostics];
    if (!metadata.codegen.canGenerateFlutter) {
      diagnostics.addAll(
        metadata.codegen.blockedReasons.map(
          (reason) => RiveCodegenDiagnostic(
            severity: RiveCodegenDiagnosticSeverity.error,
            code: 'flutterCodegenBlocked',
            message: reason,
            path: 'codegen.flutter',
          ),
        ),
      );
    }

    final prefix = _pascalIdentifier(options.classPrefix, 'RiveIntegration');
    final buffer = StringBuffer();
    if (options.includeHeader) {
      buffer
        ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
        ..writeln('// Generated by rive_telemetry_core.')
        ..writeln('// Source: ${metadata.source}')
        ..writeln();
    }
    buffer
      ..writeln("import 'dart:ui' as ui;")
      ..writeln()
      ..writeln("import 'package:rive/rive.dart' as rive;")
      ..writeln()
      ..writeln('abstract final class ${prefix}Metadata {')
      ..writeln('  static const schemaVersion = ${metadata.schemaVersion};')
      ..writeln("  static const source = ${_dartString(metadata.source)};")
      ..writeln("  static const status = '${metadata.status.name}';")
      ..writeln('}')
      ..writeln();

    _writeArtboards(buffer, prefix, metadata, plan);
    _writeStateMachines(buffer, prefix, metadata, plan);
    _writeAnimations(buffer, prefix, metadata, plan);
    _writeViewModels(buffer, prefix, metadata, plan, diagnostics);
    _writeRuntimeHelpers(buffer);

    return RiveFlutterGeneratedFile(
      source: buffer.toString(),
      diagnostics: List.unmodifiable(diagnostics),
    );
  }

  void _writeArtboards(
    StringBuffer buffer,
    String prefix,
    RiveMetadata metadata,
    RiveCodegenPlan plan,
  ) {
    buffer.writeln('abstract final class ${prefix}Artboards {');
    for (var index = 0; index < metadata.artboards.length; index++) {
      final path = 'artboards[$index]';
      final symbol = plan.symbolFor(
        kind: RiveCodegenSymbolKind.artboard,
        path: path,
      );
      buffer.writeln(
        '  static const ${symbol?.identifier ?? 'artboard${index + 1}'} = '
        '${_dartString(metadata.artboards[index].name ?? '')};',
      );
    }
    buffer
      ..writeln('}')
      ..writeln();
  }

  void _writeStateMachines(
    StringBuffer buffer,
    String prefix,
    RiveMetadata metadata,
    RiveCodegenPlan plan,
  ) {
    buffer.writeln('abstract final class ${prefix}StateMachines {');
    for (
      var artboardIndex = 0;
      artboardIndex < metadata.artboards.length;
      artboardIndex++
    ) {
      final artboardPath = 'artboards[$artboardIndex]';
      final artboardSymbol = plan.symbolFor(
        kind: RiveCodegenSymbolKind.artboard,
        path: artboardPath,
      );
      final artboard = metadata.artboards[artboardIndex];
      for (
        var stateMachineIndex = 0;
        stateMachineIndex < artboard.stateMachines.length;
        stateMachineIndex++
      ) {
        final path = '$artboardPath.stateMachines[$stateMachineIndex]';
        final stateMachineSymbol = plan.symbolFor(
          kind: RiveCodegenSymbolKind.stateMachine,
          path: path,
        );
        final identifier = _joinIdentifiers(
          artboardSymbol?.identifier ?? 'artboard${artboardIndex + 1}',
          stateMachineSymbol?.identifier ??
              'stateMachine${stateMachineIndex + 1}',
        );
        buffer.writeln(
          '  static const $identifier = '
          '${_dartString(artboard.stateMachines[stateMachineIndex].name ?? '')};',
        );
      }
    }
    buffer
      ..writeln('}')
      ..writeln();
  }

  void _writeAnimations(
    StringBuffer buffer,
    String prefix,
    RiveMetadata metadata,
    RiveCodegenPlan plan,
  ) {
    buffer.writeln('abstract final class ${prefix}Animations {');
    for (
      var artboardIndex = 0;
      artboardIndex < metadata.artboards.length;
      artboardIndex++
    ) {
      final artboardPath = 'artboards[$artboardIndex]';
      final artboardSymbol = plan.symbolFor(
        kind: RiveCodegenSymbolKind.artboard,
        path: artboardPath,
      );
      final artboard = metadata.artboards[artboardIndex];
      for (
        var animationIndex = 0;
        animationIndex < artboard.animations.length;
        animationIndex++
      ) {
        final path = '$artboardPath.animations[$animationIndex]';
        final animationSymbol = plan.symbolFor(
          kind: RiveCodegenSymbolKind.animation,
          path: path,
        );
        final identifier = _joinIdentifiers(
          artboardSymbol?.identifier ?? 'artboard${artboardIndex + 1}',
          animationSymbol?.identifier ?? 'animation${animationIndex + 1}',
        );
        buffer.writeln(
          '  static const $identifier = '
          '${_dartString(artboard.animations[animationIndex].name ?? '')};',
        );
      }
    }
    buffer
      ..writeln('}')
      ..writeln();
  }

  void _writeViewModels(
    StringBuffer buffer,
    String prefix,
    RiveMetadata metadata,
    RiveCodegenPlan plan,
    List<RiveCodegenDiagnostic> diagnostics,
  ) {
    buffer.writeln('abstract final class ${prefix}ViewModels {');
    for (var index = 0; index < metadata.viewModels.length; index++) {
      final path = 'viewModels[$index]';
      final symbol = plan.symbolFor(
        kind: RiveCodegenSymbolKind.viewModel,
        path: path,
      );
      buffer.writeln(
        '  static const ${symbol?.identifier ?? 'viewModel${index + 1}'} = '
        '${_dartString(metadata.viewModels[index].name ?? '')};',
      );
    }
    buffer
      ..writeln('}')
      ..writeln();

    for (
      var viewModelIndex = 0;
      viewModelIndex < metadata.viewModels.length;
      viewModelIndex++
    ) {
      final viewModel = metadata.viewModels[viewModelIndex];
      final viewModelPath = 'viewModels[$viewModelIndex]';
      final viewModelSymbol = plan.symbolFor(
        kind: RiveCodegenSymbolKind.viewModel,
        path: viewModelPath,
      );
      final className =
          '$prefix${_pascalIdentifier(viewModelSymbol?.identifier ?? 'viewModel${viewModelIndex + 1}', 'ViewModel')}Binding';
      buffer
        ..writeln('final class $className {')
        ..writeln('  const $className(this.instance);')
        ..writeln()
        ..writeln('  final rive.ViewModelInstance instance;')
        ..writeln()
        ..writeln(
          '  static const viewModelName = ${_dartString(viewModel.name ?? '')};',
        );

      for (
        var instanceIndex = 0;
        instanceIndex < viewModel.instances.length;
        instanceIndex++
      ) {
        final instancePath = '$viewModelPath.instances[$instanceIndex]';
        final instanceSymbol = plan.symbolFor(
          kind: RiveCodegenSymbolKind.viewModelInstance,
          path: instancePath,
        );
        buffer.writeln(
          '  static const ${_joinIdentifiers(instanceSymbol?.identifier ?? 'instance${instanceIndex + 1}', 'Name')} = '
          '${_dartString(viewModel.instances[instanceIndex].name ?? '')};',
        );
      }

      if (viewModel.instances.isNotEmpty) {
        buffer.writeln();
      }

      for (
        var propertyIndex = 0;
        propertyIndex < viewModel.properties.length;
        propertyIndex++
      ) {
        final property = viewModel.properties[propertyIndex];
        final propertyPath = '$viewModelPath.properties[$propertyIndex]';
        final propertySymbol = plan.symbolFor(
          kind: RiveCodegenSymbolKind.viewModelProperty,
          path: propertyPath,
        );
        final identifier =
            propertySymbol?.identifier ?? 'property${propertyIndex + 1}';
        final helperType = _flutterPropertyHelperType(property.type);
        if (helperType == 'RiveUnsupportedViewModelProperty') {
          diagnostics.add(
            RiveCodegenDiagnostic(
              severity: RiveCodegenDiagnosticSeverity.warning,
              code: 'unsupportedFlutterViewModelProperty',
              message:
                  'Generated metadata-only accessor for unsupported ViewModel property type ${property.type.name}.',
              path: propertyPath,
            ),
          );
        }
        buffer.writeln(
          '  $helperType get $identifier => '
          '$helperType(instance, ${_dartString(property.name ?? '')});',
        );
      }

      buffer
        ..writeln('}')
        ..writeln();
    }
  }

  void _writeRuntimeHelpers(StringBuffer buffer) {
    buffer
      ..writeln('final class RiveNumberViewModelProperty {')
      ..writeln(
        '  const RiveNumberViewModelProperty(this.instance, this.name);',
      )
      ..writeln('  final rive.ViewModelInstance instance;')
      ..writeln('  final String name;')
      ..writeln('  double? get value => instance.number(name)?.value;')
      ..writeln('  bool set(num value) {')
      ..writeln('    final property = instance.number(name);')
      ..writeln('    if (property == null) return false;')
      ..writeln('    property.value = value.toDouble();')
      ..writeln('    instance.requestAdvance();')
      ..writeln('    return true;')
      ..writeln('  }')
      ..writeln('}')
      ..writeln()
      ..writeln('final class RiveBooleanViewModelProperty {')
      ..writeln(
        '  const RiveBooleanViewModelProperty(this.instance, this.name);',
      )
      ..writeln('  final rive.ViewModelInstance instance;')
      ..writeln('  final String name;')
      ..writeln('  bool? get value => instance.boolean(name)?.value;')
      ..writeln('  bool set(bool value) {')
      ..writeln('    final property = instance.boolean(name);')
      ..writeln('    if (property == null) return false;')
      ..writeln('    property.value = value;')
      ..writeln('    instance.requestAdvance();')
      ..writeln('    return true;')
      ..writeln('  }')
      ..writeln('}')
      ..writeln()
      ..writeln('final class RiveStringViewModelProperty {')
      ..writeln(
        '  const RiveStringViewModelProperty(this.instance, this.name);',
      )
      ..writeln('  final rive.ViewModelInstance instance;')
      ..writeln('  final String name;')
      ..writeln('  String? get value => instance.string(name)?.value;')
      ..writeln('  bool set(String value) {')
      ..writeln('    final property = instance.string(name);')
      ..writeln('    if (property == null) return false;')
      ..writeln('    property.value = value;')
      ..writeln('    instance.requestAdvance();')
      ..writeln('    return true;')
      ..writeln('  }')
      ..writeln('}')
      ..writeln()
      ..writeln('final class RiveColorViewModelProperty {')
      ..writeln('  const RiveColorViewModelProperty(this.instance, this.name);')
      ..writeln('  final rive.ViewModelInstance instance;')
      ..writeln('  final String name;')
      ..writeln('  ui.Color? get value => instance.color(name)?.value;')
      ..writeln('  bool set(ui.Color value) {')
      ..writeln('    final property = instance.color(name);')
      ..writeln('    if (property == null) return false;')
      ..writeln('    property.value = value;')
      ..writeln('    instance.requestAdvance();')
      ..writeln('    return true;')
      ..writeln('  }')
      ..writeln('}')
      ..writeln()
      ..writeln('final class RiveEnumViewModelProperty {')
      ..writeln('  const RiveEnumViewModelProperty(this.instance, this.name);')
      ..writeln('  final rive.ViewModelInstance instance;')
      ..writeln('  final String name;')
      ..writeln('  String? get value => instance.enumerator(name)?.value;')
      ..writeln('  bool set(String value) {')
      ..writeln('    final property = instance.enumerator(name);')
      ..writeln('    if (property == null) return false;')
      ..writeln('    property.value = value;')
      ..writeln('    instance.requestAdvance();')
      ..writeln('    return true;')
      ..writeln('  }')
      ..writeln('}')
      ..writeln()
      ..writeln('final class RiveTriggerViewModelProperty {')
      ..writeln(
        '  const RiveTriggerViewModelProperty(this.instance, this.name);',
      )
      ..writeln('  final rive.ViewModelInstance instance;')
      ..writeln('  final String name;')
      ..writeln('  bool fire() {')
      ..writeln('    final property = instance.trigger(name);')
      ..writeln('    if (property == null) return false;')
      ..writeln('    property.trigger();')
      ..writeln('    instance.requestAdvance();')
      ..writeln('    return true;')
      ..writeln('  }')
      ..writeln('}')
      ..writeln()
      ..writeln('final class RiveUnsupportedViewModelProperty {')
      ..writeln(
        '  const RiveUnsupportedViewModelProperty(this.instance, this.name);',
      )
      ..writeln('  final rive.ViewModelInstance instance;')
      ..writeln('  final String name;')
      ..writeln('}');
  }
}

String _flutterPropertyHelperType(RiveViewModelPropertyType type) {
  return switch (type) {
    RiveViewModelPropertyType.number => 'RiveNumberViewModelProperty',
    RiveViewModelPropertyType.boolean => 'RiveBooleanViewModelProperty',
    RiveViewModelPropertyType.string => 'RiveStringViewModelProperty',
    RiveViewModelPropertyType.color => 'RiveColorViewModelProperty',
    RiveViewModelPropertyType.trigger => 'RiveTriggerViewModelProperty',
    RiveViewModelPropertyType.enumType => 'RiveEnumViewModelProperty',
    RiveViewModelPropertyType.list ||
    RiveViewModelPropertyType.viewModel ||
    RiveViewModelPropertyType.unknown => 'RiveUnsupportedViewModelProperty',
  };
}

String _joinIdentifiers(String first, String second) =>
    first + second[0].toUpperCase() + second.substring(1);

String _pascalIdentifier(String sourceName, String fallback) {
  final lowerCamel = sanitizeRiveIdentifier(sourceName, fallback: fallback);
  return lowerCamel[0].toUpperCase() + lowerCamel.substring(1);
}

String _dartString(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll('\r', r'\r')
      .replaceAll('\n', r'\n');
  return "'$escaped'";
}
