import 'codegen.dart';
import 'metadata.dart';

class RiveTypeScriptGeneratorOptions {
  const RiveTypeScriptGeneratorOptions({
    this.symbolPrefix = 'riveIntegration',
    this.includeHeader = true,
    this.includeReactStarter = true,
  });

  final String symbolPrefix;
  final bool includeHeader;
  final bool includeReactStarter;
}

class RiveTypeScriptGeneratedFile {
  const RiveTypeScriptGeneratedFile({
    required this.source,
    required this.diagnostics,
  });

  final String source;
  final List<RiveCodegenDiagnostic> diagnostics;
}

class RiveTypeScriptIntegrationGenerator {
  const RiveTypeScriptIntegrationGenerator({
    this.planner = const RiveCodegenPlanner(),
  });

  final RiveCodegenPlanner planner;

  RiveTypeScriptGeneratedFile generate(
    RiveMetadata metadata, {
    RiveTypeScriptGeneratorOptions options =
        const RiveTypeScriptGeneratorOptions(),
  }) {
    final plan = planner.build(metadata);
    final diagnostics = [...plan.diagnostics];
    if (!metadata.codegen.canGenerateTypeScript) {
      diagnostics.addAll(
        metadata.codegen.blockedReasons.map(
          (reason) => RiveCodegenDiagnostic(
            severity: RiveCodegenDiagnosticSeverity.error,
            code: 'typescriptCodegenBlocked',
            message: reason,
            path: 'codegen.typescript',
          ),
        ),
      );
    }

    final prefix = sanitizeRiveIdentifier(
      options.symbolPrefix,
      fallback: 'riveIntegration',
    );
    final buffer = StringBuffer();
    if (options.includeHeader) {
      buffer
        ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
        ..writeln('// Generated by rive_telemetry_core.')
        ..writeln('// Source: ${metadata.source}')
        ..writeln();
    }

    buffer
      ..writeln('export const ${prefix}Metadata = {')
      ..writeln('  schemaVersion: ${metadata.schemaVersion},')
      ..writeln('  source: ${_tsString(metadata.source)},')
      ..writeln('  status: ${_tsString(metadata.status.name)},')
      ..writeln('} as const;')
      ..writeln();

    _writeArtboards(buffer, prefix, metadata, plan);
    _writeStateMachines(buffer, prefix, metadata, plan);
    _writeAnimations(buffer, prefix, metadata, plan);
    _writeViewModels(buffer, prefix, metadata, plan, diagnostics);
    _writeRuntimeHelpers(buffer);
    if (options.includeReactStarter) {
      _writeReactStarter(buffer, prefix, metadata, plan);
    }

    return RiveTypeScriptGeneratedFile(
      source: buffer.toString(),
      diagnostics: List.unmodifiable(diagnostics),
    );
  }

  void _writeArtboards(
    StringBuffer buffer,
    String prefix,
    RiveMetadata metadata,
    RiveCodegenPlan plan,
  ) {
    buffer.writeln('export const ${prefix}Artboards = {');
    for (var index = 0; index < metadata.artboards.length; index++) {
      final symbol = plan.symbolFor(
        kind: RiveCodegenSymbolKind.artboard,
        path: 'artboards[$index]',
      );
      buffer.writeln(
        '  ${symbol?.identifier ?? 'artboard${index + 1}'}: '
        '${_tsString(metadata.artboards[index].name ?? '')},',
      );
    }
    buffer
      ..writeln('} as const;')
      ..writeln();
  }

  void _writeStateMachines(
    StringBuffer buffer,
    String prefix,
    RiveMetadata metadata,
    RiveCodegenPlan plan,
  ) {
    buffer.writeln('export const ${prefix}StateMachines = {');
    for (
      var artboardIndex = 0;
      artboardIndex < metadata.artboards.length;
      artboardIndex++
    ) {
      final artboardPath = 'artboards[$artboardIndex]';
      final artboardSymbol = plan.symbolFor(
        kind: RiveCodegenSymbolKind.artboard,
        path: artboardPath,
      );
      final artboard = metadata.artboards[artboardIndex];
      for (
        var stateMachineIndex = 0;
        stateMachineIndex < artboard.stateMachines.length;
        stateMachineIndex++
      ) {
        final stateMachineSymbol = plan.symbolFor(
          kind: RiveCodegenSymbolKind.stateMachine,
          path: '$artboardPath.stateMachines[$stateMachineIndex]',
        );
        final identifier = _joinIdentifiers(
          artboardSymbol?.identifier ?? 'artboard${artboardIndex + 1}',
          stateMachineSymbol?.identifier ??
              'stateMachine${stateMachineIndex + 1}',
        );
        buffer.writeln(
          '  $identifier: '
          '${_tsString(artboard.stateMachines[stateMachineIndex].name ?? '')},',
        );
      }
    }
    buffer
      ..writeln('} as const;')
      ..writeln();
  }

  void _writeAnimations(
    StringBuffer buffer,
    String prefix,
    RiveMetadata metadata,
    RiveCodegenPlan plan,
  ) {
    buffer.writeln('export const ${prefix}Animations = {');
    for (
      var artboardIndex = 0;
      artboardIndex < metadata.artboards.length;
      artboardIndex++
    ) {
      final artboardPath = 'artboards[$artboardIndex]';
      final artboardSymbol = plan.symbolFor(
        kind: RiveCodegenSymbolKind.artboard,
        path: artboardPath,
      );
      final artboard = metadata.artboards[artboardIndex];
      for (
        var animationIndex = 0;
        animationIndex < artboard.animations.length;
        animationIndex++
      ) {
        final animationSymbol = plan.symbolFor(
          kind: RiveCodegenSymbolKind.animation,
          path: '$artboardPath.animations[$animationIndex]',
        );
        final identifier = _joinIdentifiers(
          artboardSymbol?.identifier ?? 'artboard${artboardIndex + 1}',
          animationSymbol?.identifier ?? 'animation${animationIndex + 1}',
        );
        buffer.writeln(
          '  $identifier: '
          '${_tsString(artboard.animations[animationIndex].name ?? '')},',
        );
      }
    }
    buffer
      ..writeln('} as const;')
      ..writeln();
  }

  void _writeViewModels(
    StringBuffer buffer,
    String prefix,
    RiveMetadata metadata,
    RiveCodegenPlan plan,
    List<RiveCodegenDiagnostic> diagnostics,
  ) {
    buffer.writeln('export const ${prefix}ViewModels = {');
    for (var index = 0; index < metadata.viewModels.length; index++) {
      final symbol = plan.symbolFor(
        kind: RiveCodegenSymbolKind.viewModel,
        path: 'viewModels[$index]',
      );
      buffer.writeln(
        '  ${symbol?.identifier ?? 'viewModel${index + 1}'}: '
        '${_tsString(metadata.viewModels[index].name ?? '')},',
      );
    }
    buffer
      ..writeln('} as const;')
      ..writeln();

    for (
      var viewModelIndex = 0;
      viewModelIndex < metadata.viewModels.length;
      viewModelIndex++
    ) {
      final viewModel = metadata.viewModels[viewModelIndex];
      final viewModelPath = 'viewModels[$viewModelIndex]';
      final viewModelSymbol = plan.symbolFor(
        kind: RiveCodegenSymbolKind.viewModel,
        path: viewModelPath,
      );
      final factoryName = _joinIdentifiers(
        'create',
        viewModelSymbol?.identifier ?? 'viewModel${viewModelIndex + 1}',
      );
      buffer
        ..writeln(
          'export function $factoryName(instance: RiveViewModelRuntime) {',
        )
        ..writeln('  return {')
        ..writeln('    instance,')
        ..writeln('    viewModelName: ${_tsString(viewModel.name ?? '')},');

      if (viewModel.instances.isNotEmpty) {
        buffer.writeln('    instances: {');
        for (
          var instanceIndex = 0;
          instanceIndex < viewModel.instances.length;
          instanceIndex++
        ) {
          final instanceSymbol = plan.symbolFor(
            kind: RiveCodegenSymbolKind.viewModelInstance,
            path: '$viewModelPath.instances[$instanceIndex]',
          );
          buffer.writeln(
            '      ${instanceSymbol?.identifier ?? 'instance${instanceIndex + 1}'}: '
            '${_tsString(viewModel.instances[instanceIndex].name ?? '')},',
          );
        }
        buffer.writeln('    },');
      }

      for (
        var propertyIndex = 0;
        propertyIndex < viewModel.properties.length;
        propertyIndex++
      ) {
        final property = viewModel.properties[propertyIndex];
        final propertyPath = '$viewModelPath.properties[$propertyIndex]';
        final propertySymbol = plan.symbolFor(
          kind: RiveCodegenSymbolKind.viewModelProperty,
          path: propertyPath,
        );
        final identifier =
            propertySymbol?.identifier ?? 'property${propertyIndex + 1}';
        final helperCall = _typescriptPropertyHelperCall(
          property.type,
          property.name ?? '',
        );
        if (helperCall.startsWith('unsupportedProperty')) {
          diagnostics.add(
            RiveCodegenDiagnostic(
              severity: RiveCodegenDiagnosticSeverity.warning,
              code: 'unsupportedTypeScriptViewModelProperty',
              message:
                  'Generated metadata-only helper for unsupported ViewModel property type ${property.type.name}.',
              path: propertyPath,
            ),
          );
        }
        buffer.writeln('    $identifier: $helperCall,');
      }
      buffer
        ..writeln('  } as const;')
        ..writeln('}')
        ..writeln();
    }
  }

  void _writeRuntimeHelpers(StringBuffer buffer) {
    buffer
      ..writeln('export interface RiveValueRuntimeProperty<T> {')
      ..writeln('  value: T;')
      ..writeln('}')
      ..writeln()
      ..writeln('export interface RiveTriggerRuntimeProperty {')
      ..writeln('  trigger?: () => void;')
      ..writeln('  fire?: () => void;')
      ..writeln('}')
      ..writeln()
      ..writeln('export interface RiveViewModelRuntime {')
      ..writeln(
        '  number?: (name: string) => RiveValueRuntimeProperty<number> | null;',
      )
      ..writeln(
        '  boolean?: (name: string) => RiveValueRuntimeProperty<boolean> | null;',
      )
      ..writeln(
        '  string?: (name: string) => RiveValueRuntimeProperty<string> | null;',
      )
      ..writeln(
        '  color?: (name: string) => RiveValueRuntimeProperty<RiveColorValue> | null;',
      )
      ..writeln(
        '  enum?: (name: string) => RiveValueRuntimeProperty<string> | null;',
      )
      ..writeln(
        '  enumerator?: (name: string) => RiveValueRuntimeProperty<string> | null;',
      )
      ..writeln(
        '  trigger?: (name: string) => RiveTriggerRuntimeProperty | null;',
      )
      ..writeln('  requestAdvance?: () => void;')
      ..writeln('}')
      ..writeln()
      ..writeln(
        'export type RiveColorValue = string | number | { r: number; g: number; b: number; a?: number };',
      )
      ..writeln()
      ..writeln('export interface RiveValueHelper<T> {')
      ..writeln('  readonly name: string;')
      ..writeln('  readonly value: T | null;')
      ..writeln('  set(value: T): boolean;')
      ..writeln('}')
      ..writeln()
      ..writeln('export interface RiveTriggerHelper {')
      ..writeln('  readonly name: string;')
      ..writeln('  fire(): boolean;')
      ..writeln('}')
      ..writeln()
      ..writeln('function valueProperty<T>(')
      ..writeln('  instance: RiveViewModelRuntime,')
      ..writeln('  name: string,')
      ..writeln(
        "  method: 'number' | 'boolean' | 'string' | 'color' | 'enum' | 'enumerator',",
      )
      ..writeln('): RiveValueHelper<T> {')
      ..writeln('  return {')
      ..writeln('    name,')
      ..writeln('    get value(): T | null {')
      ..writeln(
        '      const property = instance[method]?.(name) as RiveValueRuntimeProperty<T> | null | undefined;',
      )
      ..writeln('      return property?.value ?? null;')
      ..writeln('    },')
      ..writeln('    set(value: T): boolean {')
      ..writeln(
        '      const property = instance[method]?.(name) as RiveValueRuntimeProperty<T> | null | undefined;',
      )
      ..writeln('      if (!property) return false;')
      ..writeln('      property.value = value;')
      ..writeln('      instance.requestAdvance?.();')
      ..writeln('      return true;')
      ..writeln('    },')
      ..writeln('  };')
      ..writeln('}')
      ..writeln()
      ..writeln('function enumProperty(')
      ..writeln('  instance: RiveViewModelRuntime,')
      ..writeln('  name: string,')
      ..writeln('): RiveValueHelper<string> {')
      ..writeln(
        "  return instance.enumerator ? valueProperty<string>(instance, name, 'enumerator') : valueProperty<string>(instance, name, 'enum');",
      )
      ..writeln('}')
      ..writeln()
      ..writeln('function triggerProperty(')
      ..writeln('  instance: RiveViewModelRuntime,')
      ..writeln('  name: string,')
      ..writeln('): RiveTriggerHelper {')
      ..writeln('  return {')
      ..writeln('    name,')
      ..writeln('    fire(): boolean {')
      ..writeln('      const property = instance.trigger?.(name);')
      ..writeln('      if (!property) return false;')
      ..writeln('      if (property.trigger) property.trigger();')
      ..writeln('      else if (property.fire) property.fire();')
      ..writeln('      else return false;')
      ..writeln('      instance.requestAdvance?.();')
      ..writeln('      return true;')
      ..writeln('    },')
      ..writeln('  };')
      ..writeln('}')
      ..writeln()
      ..writeln('function unsupportedProperty(name: string) {')
      ..writeln('  return { name, supported: false } as const;')
      ..writeln('}')
      ..writeln();
  }

  void _writeReactStarter(
    StringBuffer buffer,
    String prefix,
    RiveMetadata metadata,
    RiveCodegenPlan plan,
  ) {
    final firstArtboardSymbol = plan.symbolFor(
      kind: RiveCodegenSymbolKind.artboard,
      path: 'artboards[0]',
    );
    final firstStateMachineSymbol = plan.symbolFor(
      kind: RiveCodegenSymbolKind.stateMachine,
      path: 'artboards[0].stateMachines[0]',
    );
    final artboardReference = firstArtboardSymbol == null
        ? 'undefined'
        : '${prefix}Artboards.${firstArtboardSymbol.identifier}';
    final stateMachineReference = firstStateMachineSymbol == null
        ? 'undefined'
        : '${prefix}StateMachines.${_joinIdentifiers(firstArtboardSymbol?.identifier ?? 'artboard1', firstStateMachineSymbol.identifier)}';
    final snippet =
        '''
import { useRive } from '@rive-app/react-canvas';
import {
  ${prefix}Artboards,
  ${prefix}StateMachines,
} from './${_kebabIdentifier(prefix)}.generated';

export function RiveScene() {
  const { RiveComponent } = useRive({
    src: '/path/to/file.riv',
    artboard: $artboardReference,
    stateMachines: $stateMachineReference,
    autoplay: true,
  });

  return <RiveComponent />;
}
''';

    buffer
      ..writeln('export const ${prefix}ReactStarter = ${_tsTemplate(snippet)};')
      ..writeln();
  }
}

String _typescriptPropertyHelperCall(
  RiveViewModelPropertyType type,
  String name,
) {
  final quotedName = _tsString(name);
  return switch (type) {
    RiveViewModelPropertyType.number =>
      'valueProperty<number>(instance, $quotedName, ${_tsString('number')})',
    RiveViewModelPropertyType.boolean =>
      'valueProperty<boolean>(instance, $quotedName, ${_tsString('boolean')})',
    RiveViewModelPropertyType.string =>
      'valueProperty<string>(instance, $quotedName, ${_tsString('string')})',
    RiveViewModelPropertyType.color =>
      'valueProperty<RiveColorValue>(instance, $quotedName, ${_tsString('color')})',
    RiveViewModelPropertyType.enumType => 'enumProperty(instance, $quotedName)',
    RiveViewModelPropertyType.trigger =>
      'triggerProperty(instance, $quotedName)',
    RiveViewModelPropertyType.list ||
    RiveViewModelPropertyType.viewModel ||
    RiveViewModelPropertyType.unknown => 'unsupportedProperty($quotedName)',
  };
}

String _joinIdentifiers(String first, String second) =>
    first + second[0].toUpperCase() + second.substring(1);

String _kebabIdentifier(String value) {
  final words = RegExp(
    r'[A-Z]?[a-z]+|[A-Z]+(?![a-z])|\d+',
  ).allMatches(value).map((match) => match.group(0)!.toLowerCase()).toList();
  return words.isEmpty ? value.toLowerCase() : words.join('-');
}

String _tsString(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll('\r', r'\r')
      .replaceAll('\n', r'\n');
  return "'$escaped'";
}

String _tsTemplate(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll('`', r'\`')
      .replaceAll(r'${', r'\${');
  return '`$escaped`';
}
