name: rive_telemetry
description: "Debug Rive animations in Flutter from VS Code by inspecting and controlling state machine inputs and ViewModel properties."
version: 0.2.0
repository: https://github.com/Rimotli-tech/rive_telemetry
topics:
  - rive
  - telemetry
  - debugging
  - flutter

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.14.2
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
